### ISSUE TITLE
Hi，Could you please provide some background information about this project?

### ISSUE THREAD

**Issue by C-rayon** [kolyan288/Oil-salinity-and-water-content-sensor#1]
Hi，Could you please provide some background information about this project?

**Comment by kolyan288** [comment]
Hi, this project was developed in order to predict the salinity and water content of oil using ML, based on real data obtained from oil treatment plants. Anomaly detection is also equally important, which allows the dispatcher to take the necessary measures in advance to prevent exceeding the standard indicators.

**Comment by C-rayon** [comment]
Thank you very much for your reply!!!&nbsp;
Could you please tell me what input data you used for your model?


déjà&nbsp;vu
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kolyan288/Oil-salinity-and-water-content-sensor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月7日(星期四) 凌晨4:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [kolyan288/Oil-salinity-and-water-content-sensor] Hi，Could you please provide some background information about this project? (Issue #1)





 
Hi, this project was developed in order to predict the salinity and water content of oil using ML, based on real data obtained from oil treatment plants. Anomaly detection is also equally important, which allows the dispatcher to take the necessary measures in advance to prevent exceeding the standard indicators.

**Comment by kolyan288** [comment]
The input data were taken from the oil refining facilities of the Russian company Tatneft. The dataset is owned by the company and is not publicly available

**Comment by C-rayon** [comment]
OK. Thank you for your reply!!




déjà&nbsp;vu
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kolyan288/Oil-salinity-and-water-content-sensor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月12日(星期二) 凌晨3:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [kolyan288/Oil-salinity-and-water-content-sensor] Hi，Could you please provide some background information about this project? (Issue #1)





 
The input data were taken from the oil refining facilities of the Russian company Tatneft. The dataset is owned by the company and is not publicly available
